### PR TITLE
screenshot

### PR DESCRIPTION
**Pull request by diuguide**
Will be updating readme.

### CODE REVIEW

**Comment by thadkingcole** [comment]
@diuguide Can you review pull request #42 and bring those changes into what you're working on?

**Comment by diuguide** [comment]
ok, that looks great so do we even need the screen shot? I see a deployed GIF

**Comment by thadkingcole** [comment]
I think adding a screen shot directly under the title header and above the table of contents would look nice. Having a screenshot towards the top would show what the app looks like; then after reading about the app, the gif shows the reader how it works and what it can do.

**Comment by thadkingcole** [comment]
@diuguide We're ready to work on the presentation now :)

**Review by thadkingcole — APPROVED** [review]

**Pull request merged**
